spring:
  application:
    name: spring-1
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring_1}
    username: ${DB_USERNAME:user1}
    password: ${DB_PASSWORD:pass1234}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/dev/changelog.xml
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  show-actuator: true
  show-login-endpoint: true
  enable-spring-security: true
  show-oauth2-endpoints: true

app:
  admin:
    email: admin@gmail.com
    fullName: admin
    password: admin@1234
  jwt:
    secret: VxRfBGJFviiO62cg/M0YY5WypcyvtUUjfkI5aDJgwt4dLz6BQKuaKChKyn+Ulhz+
  cookie:
    secure: false
