[tools]
java = "21"
maven = "3.9"
spring-boot = "latest"

[tasks.start]
description = "Start server"
run = "mvn spring-boot:run"

[tasks.build]
description = "Packaging"
run = "mvn package"

[tasks.compile]
description = "Compile Java"
run = "mvn compile"
sources = ["pom.xml", "src/main/java/**/*.java", "src/main/resources/*"]

[tasks.test]
description = "Run test"
run = "mvn test"
