spring:
  application:
    name: spring-1
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring_1}
    username: ${DB_USERNAME:user1}
    password: ${DB_PASSWORD:pass1234}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/${LIQUIBASE_FOLDER:prod}/changelog.xml
    enabled: ${LIQUIBASE_ENABLED:true}

springdoc:
  swagger-ui:
    enabled: ${SWAGGERUI_ENABLED:false}
  api-docs:
    enabled: ${APIDOC_ENABLED:false}
  show-actuator: ${API_SHOW_ACTUATOR:false}
  show-login-endpoint: ${API_SHOW_LOGIN:false}
  enable-spring-security: ${API_ENABLE_SPRING_SECURITY:false}
  show-oauth2-endpoints: ${API_SHOW_OAUTH2:false}

app:
  admin:
    email: ${ADMIN_EMAIL:admin@gmail.com}
    fullName: ${ADMIN_FULLNAME:admin}
    password: ${ADMIN_PASSWORD:admin@1234}
  jwt:
    refresh:
      expiry: 300000
    access:
      expiry: 86400000
  cookie:
    secure: true
